#!/usr/bin/ruby
#Chris Wood - A00741285 - COMP8005 - Assignment 1
#Benchmark
#Use multiple processes and threads on either the Windows or Linux operating systems and measure the performance and efficiency of each mechanism.


#global variables
usage = "Proper usage: ./bench [t|p]"
num_workers = 5


#functions


#program logic
if ARGV.count > 1 || ARGV.empty?
	puts usage
	exit
elsif ARGV[0].eql? 't'
	# run threads
	puts "running threads"
elsif ARGV[0].eql? 'p'
	# run process
	puts "running processes"
else 
	puts usage
end
